version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./prisma:/app/prisma
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npx prisma generate && npm run dev"
  db:
    image: mongo:8
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
volumes:
  mongo-data:
